создан статус бар
Mihtogan/cactomView pull request #1
Opened 2024-11-07 16:17 UTC by Mihtogan

2024-11-07 16:30 UTC, bogomazov-std requested changes

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
Почитать что это такое и как это убрать

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +        val view: StatusBarView = findViewById(R.id.statusBar)
Использовать ViewBinding

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +            StatusElement(Color.BLUE, 0.3f),
Использовать целочисленные значения

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    context: Context, attributes: AttributeSet? = null, defStyleRes: Int = 0,
Добавить переносы строки

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +class StatusBarView @JvmOverloads constructor(
Переименовать класс, на самом деле это не статус бар

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val defWidth = 500
Вынести в константы

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val defDrawMode = 0
Тоже

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val defColorBackground = Color.BLACK
Тоже

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val defGap = 0.01f
И тут

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val defStatuses = listOf(
Можно убрать

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val drawOptions by lazy { setOf(drawOption1()) }
Зачем тут set?

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private var widthView = defWidth
Это minHeight и minWidth

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private var rounding = defRounding
Переименовать

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +        val attrs = context.obtainStyledAttributes(attributes, R.styleable.StatusBarView)
```
context.withStyledAttributes(set, R.styleable.custom_card_view) {
    val myString = getString(R.styleable.custom_card_view_command)
}
```

Можно использовать kotlin ext

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +        val heightSize = MeasureSpec.getSize(heightMeasureSpec)
Можно упростить

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private fun drawOption1(): Bitmap {
Можно не создавать bitmap

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
Добавить анимацию заполнения

2024-11-07 16:30 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
ValueAnimator

2024-11-07 16:31 UTC, bogomazov-std commented
Переименовать проект

2024-11-09 06:54 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/statusbar/StatusBarView.kt
> +    private val drawOptions by lazy { setOf(drawOption1()) }
в нем будет набор функций для разной отрисовки

2024-11-12 05:23 UTC, bogomazov-std requested changes

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
А что с этим?

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +        val view: MaterialUsageIndicator = findViewById(R.id.statusBar)
Подключи viewBInding

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/DrawStat.kt
> +data class DrawStat(
Перенеси  в View он используется только там

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +    private val paintBack = Paint().apply {
typo что за back?

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +    private val path = Path()
Rect и Path для чего?

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +            drawOptionAnimat2,
Переименуй, чтобы было понятно что за типы отрисовки

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        private const val defAnimationTime = 2000
Константы пишем в таком стиле

```
DEFAULT_HEIGHT = 60
DEFAUTL_WIDTH = 500
```

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        private const val defWidth = 500
Давай у тебя не будет defWidth и defHeight, пусть оно само считается когда размещаешь ее на экране, если нужно ограничение, то можно обрабатывать minHeight и minWidth

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        widthView = resolveSize(defWidth, widthMeasureSpec)
Насколько я понимаю, если сейчас пользователь поставить wrap_content, и если он будет больше чем твоя view, то на экране мы увидем `defWidth `, потому-что он не займет все доступное место

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        widthView = resolveSize(defWidth, widthMeasureSpec)
Может ошибаюсь, но кажется что так

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        post {
А зачем post?

2024-11-12 05:23 UTC, bogomazov-std commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="350dp"
Попрбуй `wrap_content`

2024-11-12 13:27 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        post {
чтоб дождаться окончания расчета размера. по сути нужно только при первом вызове когда вью еще не померилась

2024-11-12 14:14 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +    private val path = Path()
балавство с новоым инструментом

2024-11-13 05:00 UTC, bogomazov-std commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        post {
А measureWidth не работате?

2024-11-13 05:01 UTC, bogomazov-std commented on app/src/main/res/values/attrs.xml
> +    </declare-styleable>
Всегда старайся добавлять название view в атрибуты, в таком случае не будет пересечений и будет легче их использовать

statusBar_drawMode

Что-то такое

2024-11-13 12:30 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        widthView = resolveSize(defWidth, widthMeasureSpec)
вроде же так и должно быть? при врапконтент вью становится какого захочет размера, но не больше доступного

2024-11-13 14:16 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
яндекс смог найти лишь несколько статей с кодом в котором есть эта анатация. жбт пишет: @SuppressLint("MissingInflatedId") — это аннотация, которая используется, чтобы подавить предупреждение о том, что метод findViewById не может найти элемент, потому что идентификатор отсутствует или не был "надут" (inflated), т.е. инициализирован в представлении (View). хотя я ищу вью после сетконтент

2024-11-13 14:17 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
может просто какой то временный баг

2024-11-13 14:41 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        post {
он доступен после межр. возможно активити вызывает сетСтатус еще до межира. можно переопределить онЛаяут или онСайз, но это поможет лишь при расчете размеров и при очередном вызове сет ничего не произойдет, хотя наверное можно еще чтото придумать. можно создать листенер завершения отрисовки, но вреде тоже самое получится. думаю всеже остановится на пост, так как он просто ткладывает выполнение до окончания расчета размера, надо только попробовать нормальноли он работает при повторных вызовах сет. както так

2024-11-13 14:44 UTC, Mihtogan commented on app/src/main/java/com/example/castomview/statusbar/MaterialUsageIndicator.kt
> +        post {
роде нормально работает

2024-11-16 04:52 UTC, merged